=== yuvakvechheka/workspace/Programmierung III Workspace/Assignment 1 (Yuvakvechheka som, Dogan Bezek)/Assignment1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    
    <!-- Element Labor anlegen -->
    <xs:element name="labor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="rechner" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="software" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="geräte"/>
            </xs:sequence>
            <!-- Atrribute von Labor spezifizieren -->
            <xs:attribute name="raumnummer" type="xs:ID" use="required"/>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Element Rechner anlegen -->
    <xs:element name="rechner">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="betriebssystem" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="anschaffungsdatum" type="xs:date"></xs:element>
                <xs:element name="anwendungssoftware" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="erweiterung">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="beschreibung"/>
                            <xs:element ref="besonderheit" minOccurs="0"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <!--  -->
            <xs:attribute name="key" use="required" type="xs:ID"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Element Software anlegen -->
    <xs:element name="software">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="beschreibung"/>
                <xs:element ref="besonderheit" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="key" use="required" type="xs:ID"/>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="lizenz" type="xs:boolean" default="true"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Element Geräte anlegen -->
    <xs:element name="geräte">
        <xs:complexType>
            <xs:sequence>
                <!-- Scanner -->
                <xs:element name="scanner">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- Scannermodel min. 1 -->
                            <xs:element name="model" maxOccurs="1"/>
                            <xs:element ref="beschreibung"/>
                            <xs:element ref="besonderheit" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="drucker">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- Drucker -->
                            <xs:element name="model" maxOccurs="1"/>
                            <xs:element ref="beschreibung"/>
                            <xs:element ref="besonderheit" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Element Beschreibung anlegen -->
    <xs:element name="beschreibung">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="festplatte" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="size" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="speicher" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="size" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="hersteller" type="xs:string" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Besonderheiten anlegen -->
    <xs:element name="besonderheit" type="xs:string"/>
    
    <!-- Element Labore anlegen -->
    <xs:element name="labore">
        <xs:complexType>
            <xs:sequence>
                <!-- Element Labore muss mindestens ein Labor Element haben-->
                <xs:element ref="labor" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <!-- ID für Rechner verbinden -->
        <xs:key name="id_rechner">
            <xs:selector xpath="./rechner"/>
            <xs:field xpath="@key"/>
        </xs:key>
        <!-- ID für Software verbinden -->
        <xs:key name="id_software">
            <xs:selector xpath="./software"/>
            <xs:field xpath="@key"/>
        </xs:key>
    </xs:element>
    
</xs:schema>

=== yuvakvechheka/workspace/Programmierung III Workspace/Assignment 1 (Yuvakvechheka som, Dogan Bezek)/Assignment1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Assignment1.xsl"?>
<labore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Users/yuvakvechhekasom/Programmierung%20III%20Workspace/Assignment%201%20(Yuvakvechheka%20som,%20Dogan%20Bezek)/Assignment1.xsd">
    
    <!-- Projektraum Umland -->
    <labor raumnummer="Z2001" name="ProjektraumU">
        
        <!-- Rechner Mac -->
        <rechner key="S111">
            <betriebssystem>IOS 10.2</betriebssystem>
            <anschaffungsdatum>2016-01-01</anschaffungsdatum>
            <anwendungssoftware>Hallo</anwendungssoftware>
            <erweiterung>
                <beschreibung>
                    <festplatte size="1TB"/>
                    <speicher size="8GB"/>
                    <hersteller>Apple</hersteller>
                </beschreibung>
            </erweiterung>
        </rechner>
        
        <!-- Rechner Lenovo -->
        <rechner key="R002">
            <betriebssystem>Windows 10</betriebssystem>
            <anschaffungsdatum>2018-01-01</anschaffungsdatum>
            <anwendungssoftware>Microsoft Office</anwendungssoftware>
            <erweiterung>
                <beschreibung>
                    <festplatte size="1TB"/>
                    <speicher size="8GB"/>
                    <hersteller>Lenovo</hersteller>
                </beschreibung>
                <besonderheit>Mickey Mouse Sticker</besonderheit>
            </erweiterung>
        </rechner>
        
        <!-- Sofware Blender  -->
        <software key="S001" name="Blender" lizenz="true">
                <beschreibung>
                    <hersteller>Blender Foundation</hersteller>
                </beschreibung>
                <besonderheit>Vorab Version seit 20.Juni 2017</besonderheit>
            
        </software>
        
        <!-- Sofware Itunes -->
        <software key="S002" name="Itunes" lizenz="true">
            <beschreibung>
                <hersteller>Apple</hersteller>
            </beschreibung>
        </software>
        
        <!-- Geräte im ProjektraumU -->
        <geräte>
            <!-- Scanner Hewlett Packard -->
            <scanner>
                <model>HP 6005</model>
                <beschreibung>
                    <hersteller>Hewlett Packard</hersteller>
                </beschreibung>
            </scanner>
            
            <!-- Drucker Brother -->
            <drucker>
                <model>Brother 203</model>
                <beschreibung>
                    <hersteller>Brother</hersteller>
                </beschreibung>
            </drucker>
        </geräte>
    </labor>
    
    <!-- Projektraum Kelb  -->
    <labor raumnummer="Z2002" name="ProjektraumK">
        
        <!-- Rechner Apple -->
        <rechner key="R003">
            <betriebssystem>MacOS Sierra</betriebssystem>
            <anschaffungsdatum>2017-06-07</anschaffungsdatum>
            <anwendungssoftware>Eclipse</anwendungssoftware>
            <erweiterung>
                <beschreibung>
                    <festplatte size="4TB"/>
                    <speicher size="16GB"/>
                    <hersteller>Apple</hersteller>
                </beschreibung>
                <besonderheit>Bildschirm Touchscreen</besonderheit>
            </erweiterung>
        </rechner>
        
        <!-- Rechner Dell -->
        <rechner key="R004">
            <betriebssystem>Linux</betriebssystem>
            <anschaffungsdatum>2015-10-12</anschaffungsdatum>
            <anwendungssoftware>SAP</anwendungssoftware>
            <erweiterung>
                <beschreibung>
                    <festplatte size="1TB"/>
                    <speicher size="16GB"/>
                    <hersteller>Dell</hersteller>
                </beschreibung>
                <besonderheit>Fingerscanner</besonderheit>
            </erweiterung>
        </rechner>
        
        <!-- Rechner Acer  -->
        <rechner key="R005">
            <betriebssystem>Windows 10</betriebssystem>
            <anschaffungsdatum>2016-02-01</anschaffungsdatum>
            <anwendungssoftware>Wikitude</anwendungssoftware>
            <erweiterung>
                <beschreibung>
                    <festplatte size="2TB"/>
                    <speicher size="16GB"/>
                    <hersteller>Acer</hersteller>
                </beschreibung>
                <besonderheit>Doppelmonitor</besonderheit>
            </erweiterung>
        </rechner>
        
        <!-- Software PyCharm CE -->
        <software key="S003" name="PyCharm CE" lizenz="true">
            <beschreibung>
                <hersteller>PyCharm CE</hersteller>
            </beschreibung>
        </software>
        
        <!-- Unity -->
        <software key="S004" name="Unity" lizenz="true">
            <beschreibung>
                <hersteller>Unity Technologies</hersteller>
            </beschreibung>
        </software>
        
        <!-- Geräte im Software-Entwicklungslabor -->
        <geräte>
            
            <!-- Beamer Acer -->
            <scanner>
                <model>A547</model>
                <beschreibung>
                    <hersteller>Acer</hersteller>
                </beschreibung>
            </scanner>
            
            <!-- Drucker HP -->
            <drucker>
                <model>HP 2003</model>
                <beschreibung>
                    <hersteller>Hewlett Packard</hersteller>
                </beschreibung>
            </drucker>
        </geräte>
    </labor>
</labore>
